import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";
import fs from "node:fs";
import path from "node:path";

// ==================== 常量定义 ====================
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outDir = "dist";

// ==================== CSS 收集 ====================
const cssRoot = path.join(process.cwd(), "src");
const cssDest = path.join(process.cwd(), outDir, "styles.css");

function collectCssFiles(dir) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...collectCssFiles(full));
    } else if (entry.isFile() && entry.name.endsWith(".css")) {
      results.push(full);
    }
  }
  return results;
}

async function buildCSS() {
  const cssFiles = collectCssFiles(cssRoot).sort();
  if (!cssFiles.length) {
    if (fs.existsSync(cssDest)) fs.unlinkSync(cssDest);
    return;
  }
  const parts = cssFiles.map((file) => {
    const rel = path.relative(process.cwd(), file);
    return `/* ${rel} */\n${fs.readFileSync(file, "utf8")}`;
  });
  const combined = parts.join("\n\n");
  const result = await esbuild.transform(combined, {
    loader: "css",
    minify: prod,
  });
  fs.writeFileSync(cssDest, result.code);
}

// ==================== 复制静态文件 ====================
function copyManifest() {
  fs.mkdirSync(path.join(process.cwd(), outDir), { recursive: true });
  const src = path.join(process.cwd(), "manifest.json");
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(process.cwd(), outDir, "manifest.json"));
  }
}

// ==================== 监听函数 ====================
// 监听 manifest.json 变化（带防抖和内容比较）
function watchManifest() {
  const manifestPath = path.join(process.cwd(), "manifest.json");

  if (!fs.existsSync(manifestPath)) {
    return;
  }

  let copyTimer = null;
  let lastContent = fs.readFileSync(manifestPath, "utf8");

  fs.watch(manifestPath, () => {
    if (copyTimer) {
      clearTimeout(copyTimer);
    }
    copyTimer = setTimeout(() => {
      try {
        const newContent = fs.readFileSync(manifestPath, "utf8");
        if (newContent !== lastContent) {
          lastContent = newContent;
          const dest = path.join(process.cwd(), outDir, "manifest.json");
          fs.copyFileSync(manifestPath, dest);
        }
      } catch (e) {
        console.error("⚠ 读取 manifest.json 失败:", e.message);
      }
      copyTimer = null;
    }, 100);
  });
}

// 监听 src/ 下的 CSS 文件变化
function watchCSS() {
  if (!fs.existsSync(cssRoot)) return;
  let timer = null;
  fs.watch(cssRoot, { recursive: true }, (_event, filename) => {
    if (filename && filename.endsWith(".css")) {
      if (timer) clearTimeout(timer);
      timer = setTimeout(() => {
        void buildCSS();
        timer = null;
      }, 100);
    }
  });
}

// ==================== 创建 esbuild context ====================
const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: outDir,
  minify: prod,
});

// ==================== 主执行逻辑 ====================
async function main() {
  // 确保 dist 目录存在
  fs.mkdirSync(path.join(process.cwd(), outDir), { recursive: true });

  // 初始构建 CSS 和 manifest
  await buildCSS();
  copyManifest();

  if (prod) {
    // 生产模式：构建并退出
    await context.rebuild();
    process.exit(0);
  } else {
    // 开发模式：启动监听
    watchManifest();
    watchCSS();
    await context.watch();
  }
}

main().catch((error) => {
  console.error("构建失败:", error);
  process.exit(1);
});
