blank_issues_enabled: false
contact_links:
    - name: 💬 Discussion | 讨论区
      url: https://github.com/TracingOrigins/obsidian-fast-copier-plugin/discussions
      about: Please ask and answer questions here. | 请在这里提问或讨论。
